//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyPermissionDetail
    {
        public int SPId { get; set; }
        public int PId { get; set; }
        public string SName { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual product product { get; set; }
        public virtual store store { get; set; }
        public virtual SupplyPermision SupplyPermision { get; set; }
    }
}
